# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23c30648ed38ec36c92c87f29e1e1626a6eaf7ae906aeed2b25780422e1c3d2d2451d0a7fa9fa66576d5f409f874840459fe84ebf93296797e089916fac3541d

test:
  secret_key_base: 6c48e38d0564f8160206f6ec05cebca636974e92b868e3916cf00a10eb87578c67b49e47d856695763d6207a9c273251a359142fc95232a09f3bceb9db276942

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
